export enum ErrorCode {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_USER_EXISTS = 'AUTH_USER_EXISTS',
  CENTER_ACCESS_DENIED = 'CENTER_ACCESS_DENIED',

  // Booking & Slots
  BOOKING_SLOT_FULL = 'BOOKING_SLOT_FULL',
  BOOKING_ALREADY_ACTIVE = 'BOOKING_ALREADY_ACTIVE',
  BOOKING_INVALID_SLOT = 'BOOKING_INVALID_SLOT',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',

  // Queue
  QUEUE_NOT_FOUND = 'QUEUE_NOT_FOUND',
  QUEUE_EMPTY = 'QUEUE_EMPTY',
  QUEUE_TOKEN_NOT_WAITING = 'QUEUE_TOKEN_NOT_WAITING',

  // Procurement Lifecycle
  PROCUREMENT_NOT_FOUND = 'PROCUREMENT_NOT_FOUND',
  PROCUREMENT_INVALID_TRANSITION = 'PROCUREMENT_INVALID_TRANSITION',
  QUALITY_CHECK_FAILED = 'QUALITY_CHECK_FAILED',
  WEIGHMENT_INVALID_WEIGHT = 'WEIGHMENT_INVALID_WEIGHT',

  // General Validation & System
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
